all:
	make -C mimg     
	make -C simpleio        
	make -C userio     
	make -C winio  

clean:
	make -C mimg               clean
	make -C simpleio           clean
	make -C userio             clean
	make -C winio              clean